const mongoose=require('mongoose');
const teacherregister=mongoose.Schema({
    _id:mongoose.Types.ObjectId,
    teachername:{type:String,required:true},
    email:{type:String,required:true},
    password:{type:String, required:true},

    semster1:{type:String,default:'null'},
    SemSter1sectionA:{type:String,default:null},
    Semster1SectionASubject:{type:String,default:null},
    SemSter1sectionB:{type:String,default:null},
    Semster1SectionBSubject:{type:String,default:null},
    SemSter1sectionC:{type:String,default:null},
    Semster1SectionCSubject:{type:String,default:null},

    semster2:{type:String,default:null}, 
    SemSter2sectionA:{type:String,default:null},
    Semster2SectionASubject:{type:String,default:null},
    SemSter2sectionB:{type:String,default:null},
    Semster2SectionBSubject:{type:String,default:null},
    SemSter2sectionC:{type:String,default:null},
    Semster2SectionCSubject:{type:String,default:null},

    semster3:{type:String,default:null},
    SemSter3sectionA:{type:String,default:null},
    Semster3SectionASubject:{type:String,default:null},
    SemSter3sectionB:{type:String,default:null},
    Semster3SectionBSubject:{type:String,default:null},
    SemSter3sectionC:{type:String,default:null},
    Semster3SectionCSubject:{type:String,default:null},

    semster4:{type:String,default:null},
    SemSter4sectionA:{type:String,default:null},
    Semster4SectionASubject:{type:String,default:null},
    SemSter4sectionB:{type:String,default:null},
    Semster4SectionBSubject:{type:String,default:null},
    SemSter4sectionC:{type:String,default:null},
    Semster4SectionCSubject:{type:String,default:null},

    semster5:{type:String,default:null},
    SemSter5sectionA:{type:String,default:null},
    Semster5SectionASubject:{type:String,default:null},
    SemSter5sectionB:{type:String,default:null},
    Semster5SectionBSubject:{type:String,default:null},
    SemSter5sectionC:{type:String,default:null},
    Semster5SectionCSubject:{type:String,default:null},

    semster6:{type:String,default:null},
    SemSter6sectionA:{type:String,default:null},
    Semster6SectionASubject:{type:String,default:null},
    SemSter6sectionB:{type:String,default:null},
    Semster6SectionBSubject:{type:String,default:null},
    SemSter6sectionC:{type:String,default:null},
    Semster6SectionCSubject:{type:String,default:null},

    semster7:{type:String,default:null},
    SemSter7sectionA:{type:String,default:null},
    Semster7SectionASubject:{type:String,default:null},
    SemSter7sectionB:{type:String,default:null},
    Semster7SectionBSubject:{type:String,default:null},
    SemSter7sectionC:{type:String,default:null},
    Semster7SectionCSubject:{type:String,default:null},

    semster8:{type:String,default:null},
    SemSter8sectionA:{type:String,default:null},
    Semster8SectionASubject:{type:String,default:null},
    SemSter8sectionB:{type:String,default:null},
    Semster8SectionBSubject:{type:String,default:null},
    SemSter8sectionC:{type:String,default:null},
    Semster8SectionCSubject:{type:String,default:null},
});
module.exports=mongoose.model('Teacherregister',teacherregister);
